#!/usr/bin/env bash
# bin/compile <build-dir> <cache-dir>

set -e
set -o pipefail

ocaml_url=http://codefirst.org/mzp/ocaml-4.00.tgz
opam_url=http://codefirst.org/mzp/opam-full-1.0.tgz

BUILD_DIR=$1
CACHE_DIR=$2

function indent() {
  c='s/^/       /'
  case $(uname) in
    Darwin) sed -l "$c";;
    *)      sed -u "$c";;
  esac
}

function setup() {
  dir=$1
  url=$2

  rm -fr $dir
  mkdir -p $dir
  echo "fetching $url"
  curl  $url -s -o - | tar xzf - -C $dir
}

cd $BUILD_DIR
echo "-----> Fetching OCaml binaries"
setup /tmp/ocaml $ocaml_url
setup /tmp/opam  $opam_url

export PATH="/tmp/ocaml/bin:/tmp/opam/bin:$PATH"
mkdir -p /tmp/opam-lib
opam init --root=/tmp/opam-lib -y
source /tmp/opam-lib/opam-init/init.sh
opam install -y ocamlfind ocamlnet
