#!/usr/bin/env bash
# bin/compile <build-dir> <cache-dir>

set -e
set -o pipefail

ocaml_url=http://codefirst.org/mzp/eliom/ocaml-4.00.tgz
opam_url=http://codefirst.org/mzp/eliom/opam-full-1.0.tgz

BUILD_DIR=$1
CACHE_DIR=$2

function indent() {
  c='s/^/       /'
  case $(uname) in
    Darwin) sed -l "$c";;
    *)      sed -u "$c";;
  esac
}

function setup() {
  dir=$1
  url=$2

  mkdir -p $dir
  echo "fetching $url"
  curl  $url -s -o - | tar xzf - -C $dir
}

cd $BUILD_DIR
echo "-----> Fetching OCaml binaries"
setup /app/vendor/ocaml $ocaml_url
setup /app/vendor/opam  $opam_url
setup /app/ https://s3-eu-west-1.amazonaws.com/midgard-heroku/pcre.tar.gz
setup /app/vendor/gdbm http://codefirst.org/mzp/gdbm-1.tgz

echo "-----> Fetching OPAM binaries"
export PATH="/app/vendor/pcre/bin:/app/vendor/ocaml/bin:/app/vendor/opam/bin:$PATH"
ls /app
ls /app/vendor
ls /app/vendor/gdbm
which pcre-config
mkdir -p /app/vendor/opam-lib
opam init --root=/app/vendor/opam-lib -y
source /app/vendor/opam-lib/opam-init/init.sh
opam remote add myrepo https://github.com/mzp/opam-repo.git
export LD_PRELOAD=/app/vendor/pcre/lib/libpcre.so.1
opam install -v -y eliom
